# Generated by Django 5.0.7 on 2024-07-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeShops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coffeeshop',
            table='coffeeShopsTable',
        ),
    ]
