# Generated by Django 5.0.7 on 2024-07-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeShops', '0002_alter_coffeeshop_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coffeeshop',
            table='coffeeShopTable',
        ),
    ]
